# Generated by Django 5.0.6 on 2026-02-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_density',
            field=models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable'), ('spacious', 'Spacious')], default='comfortable', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='ui_theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('darker', 'Darker'), ('midnight', 'Midnight')], default='dark', max_length=20),
        ),
    ]
