# Generated by Django 5.0.6 on 2026-02-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
