# Generated by Django 5.0.6 on 2026-02-25 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_share_screenshot_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('hourly', 'A cada hora'), ('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_on_failure_only', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='testing.testproject')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
