# Generated by Django 5.0.6 on 2026-02-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_scheduledtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='video_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
