# Generated by Django 5.0.6 on 2026-02-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='discord_webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspace',
            name='slack_webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
