# Generated by Django 5.0.6 on 2026-02-25 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_discord_webhook_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspaceinvitation',
            unique_together={('workspace', 'email')},
        ),
    ]
