# Generated by Django 5.0.6 on 2026-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_workspaceinvitation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='runs_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='runs_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
